{
  "_from": "@fastify/error@^3.4.0",
  "_id": "@fastify/error@3.4.1",
  "_inBundle": false,
  "_integrity": "sha512-wWSvph+29GR783IhmvdwWnN4bUxTD01Vm5Xad4i7i1VuAOItLvbPAb69sb0IQ2N57yprvhNIwAP5B6xfKTmjmQ==",
  "_location": "/@fastify/error",
  "_phantomChildren": {},
  "_requested": {
    "type": "range",
    "registry": true,
    "raw": "@fastify/error@^3.4.0",
    "name": "@fastify/error",
    "escapedName": "@fastify%2ferror",
    "scope": "@fastify",
    "rawSpec": "^3.4.0",
    "saveSpec": null,
    "fetchSpec": "^3.4.0"
  },
  "_requiredBy": [
    "/avvio",
    "/fastify"
  ],
  "_resolved": "https://registry.npmjs.org/@fastify/error/-/error-3.4.1.tgz",
  "_shasum": "b14bb4cac3dd4ec614becbc643d1511331a6425c",
  "_spec": "@fastify/error@^3.4.0",
  "_where": "/code/server/node_modules/fastify",
  "author": {
    "name": "Tomas Della Vedova"
  },
  "bugs": {
    "url": "https://github.com/fastify/fastify-error/issues"
  },
  "bundleDependencies": false,
  "deprecated": false,
  "description": "A small utility, used by Fastify itself, for generating consistent error objects across your codebase and plugins.",
  "devDependencies": {
    "benchmark": "^2.1.4",
    "standard": "^17.0.0",
    "tap": "^16.0.0",
    "tsd": "^0.29.0"
  },
  "homepage": "https://github.com/fastify/fastify-error#readme",
  "keywords": [
    "fastify",
    "error",
    "utility",
    "plugin"
  ],
  "license": "MIT",
  "main": "index.js",
  "name": "@fastify/error",
  "publishConfig": {
    "access": "public"
  },
  "repository": {
    "type": "git",
    "url": "git+https://github.com/fastify/fastify-error.git"
  },
  "scripts": {
    "lint": "standard",
    "lint:fix": "standard --fix",
    "test": "npm run test:unit && npm run test:typescript",
    "test:typescript": "tsd",
    "test:unit": "tap"
  },
  "tsd": {
    "compilerOptions": {
      "esModuleInterop": true
    }
  },
  "type": "commonjs",
  "types": "types/index.d.ts",
  "version": "3.4.1"
}
